#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd $DIR

cat logo.txt

_LATEST=$(npm view npr-one version)
_CURRENT=$(node version.js)
_TEMPLATE='pm2.service'
_SERVICE='/etc/systemd/system/pm2.service'
_RELEASE='/etc/os-release'

if [ -f $_RELEASE ]; then

  source $_RELEASE

  if [ ID == 'rasbian' ] && [ ! -f $_SERVICE ]; then
    sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
    sudo cp $_TEMPLATE $_SERVICE
    sudo systemctl enable $_SERVICE
    sudo systemctl start $_SERVICE
  fi

fi

if [ $_CURRENT != $_LATEST ]; then
  echo "updating..."
  npm install -g npr-one &> /dev/null
fi

node index.js
